nelmio_api_doc:
    models: { use_jms: false }

    documentation:
        info:
            title: Vending Machine API
            description: This the API to control the vending machine.
            version: 1.0.0

    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api(?!/(re)?doc((\.json)|s)?$) # Accepts routes under /api except /api/doc
                - ^/auth/
                - ^/frontend/

